from contextlib import contextmanager
from pathlib import Path
import time
from typing import Any, Iterator

from synapse_mcp.core import background_jobs, credentials, dumps, evidence, scope, workspace


@contextmanager
def isolated_state(tmp_path: Path) -> Iterator[None]:
    old_workspaces_dir = workspace.WORKSPACES_DIR
    old_reports_dir = workspace.REPORTS_DIR
    old_dump_dir = dumps.DUMP_DIR
    old_scope_file = scope.SCOPE_FILE
    old_credentials_file = credentials.CREDENTIALS_FILE
    old_evidence_dir = evidence.EVIDENCE_DIR
    old_evidence_log = evidence.EVIDENCE_LOG
    old_orgs_dir = evidence.ORGS_DIR
    workspace.WORKSPACES_DIR = tmp_path / "workspaces"
    workspace.REPORTS_DIR = tmp_path / "reports"
    dumps.DUMP_DIR = workspace.WORKSPACES_DIR
    scope.SCOPE_FILE = tmp_path / "scope.json"
    credentials.CREDENTIALS_FILE = tmp_path / "credentials.json"
    evidence.EVIDENCE_DIR = tmp_path / "evidence"
    evidence.EVIDENCE_LOG = evidence.EVIDENCE_DIR / "events.jsonl"
    evidence.ORGS_DIR = evidence.EVIDENCE_DIR / "orgs"
    try:
        yield
    finally:
        workspace.WORKSPACES_DIR = old_workspaces_dir
        workspace.REPORTS_DIR = old_reports_dir
        dumps.DUMP_DIR = old_dump_dir
        scope.SCOPE_FILE = old_scope_file
        credentials.CREDENTIALS_FILE = old_credentials_file
        evidence.EVIDENCE_DIR = old_evidence_dir
        evidence.EVIDENCE_LOG = old_evidence_log
        evidence.ORGS_DIR = old_orgs_dir


def assert_shared_html_shell(testcase, content: str) -> None:
    testcase.assertTrue(content.startswith("<!doctype html>\n<html><head><meta charset=\"utf-8\">"))
    testcase.assertIn('<meta name="viewport" content="width=device-width,initial-scale=1">', content)
    testcase.assertLess(content.index('<meta name="viewport"'), content.index("<title>"))
    testcase.assertEqual(content.count("<style>"), 1)
    testcase.assertEqual(content.count("</style>"), 1)
    testcase.assertIn("synapse-report-footer", content)
    testcase.assertIn("Generated by Synapse", content)
    # Operator opted into the design-template typography served from Google Fonts.
    # The faces load as a progressive enhancement; a system-font fallback stays in
    # the inline CSS so the report still renders fully offline.
    testcase.assertIn("fonts.googleapis.com", content)
    testcase.assertIn("system-ui", content)


def wait_for_job(job_id: str, *, timeout_seconds: float = 10, require_finalized: bool = True) -> dict[str, Any]:
    deadline = time.monotonic() + timeout_seconds
    job: dict[str, Any] = {}
    while time.monotonic() < deadline:
        job = background_jobs.status(job_id, include_result=True)
        if str(job.get("status")) in {"completed", "timed_out", "failed", "canceled"}:
            if not require_finalized or job.get("finalized"):
                return job
        time.sleep(0.05)
    return job
