# Copyright 2026 Javier Roldán Ortiz
# SPDX-License-Identifier: Apache-2.0

"""Typed application action contracts."""

from .contracts import (
    ActionInput,
    ActionOutput,
    InputContractDocument,
    JsonObjectActionOutput,
    make_input_model,
    make_json_object_output_model,
)
from .descriptor import (
    ActionDescriptor,
    ActionEffectResolver,
    ActionIntentResolver,
    ActionExecutor,
    ActionRequest,
    AvailabilityResolver,
    ExecutionContext,
)
from .identity import ActionId
from .outcomes import (
    ActionOutcome,
    ApprovalRequired,
    ExecutionFailure,
    ExecutionUnknown,
    PolicyDenial,
    Success,
    UnavailableCapability,
    ValidationFailure,
    legacy_payload_signals_error,
    outcome_from_mcp_error,
    success_from_legacy_payload,
)
from .policies import (
    Availability,
    ActionEffects,
    CredentialAccess,
    CredentialPolicy,
    CredentialRequirement,
    DeadlineTier,
    Enforcement,
    Idempotency,
    IdempotencyPolicy,
    RiskClass,
    ScopePolicy,
    ScopeRequirement,
    SideEffectClass,
    LocalWriteDomain,
    TrafficDestination,
    TaskPolicy,
)
from .registry import (
    ActionRegistry,
    PassThroughPolicyEvaluator,
    PolicyEvaluationResult,
    PolicyEvaluator,
    ProfilePolicyEvaluator,
    REGISTRY,
)
from synapse_mcp.core.execution import (
    AuthorizationIntent,
    CanonicalTarget,
    ContinuationLineage,
    ExecutionPlan,
    ExecutionPlanError,
    LocalOutputDestination,
    ProviderRoute,
    RedirectPolicy,
    ScopeSnapshot,
    TargetEnvelope,
    TargetSelector,
)
from synapse_mcp.app.capability_packs.loader import assemble_capability_packs


CAPABILITY_PACKS = assemble_capability_packs(registry=REGISTRY)

__all__ = [
    "ActionDescriptor",
    "ActionEffectResolver",
    "ActionIntentResolver",
    "ActionEffects",
    "ActionExecutor",
    "ActionId",
    "ActionInput",
    "ActionOutcome",
    "ActionOutput",
    "ActionRequest",
    "ActionRegistry",
    "ApprovalRequired",
    "AuthorizationIntent",
    "Availability",
    "AvailabilityResolver",
    "CredentialAccess",
    "CredentialPolicy",
    "CredentialRequirement",
    "CanonicalTarget",
    "CAPABILITY_PACKS",
    "ContinuationLineage",
    "DeadlineTier",
    "Enforcement",
    "ExecutionContext",
    "ExecutionPlan",
    "ExecutionPlanError",
    "ExecutionFailure",
    "ExecutionUnknown",
    "Idempotency",
    "IdempotencyPolicy",
    "InputContractDocument",
    "JsonObjectActionOutput",
    "LocalWriteDomain",
    "LocalOutputDestination",
    "PolicyDenial",
    "PolicyEvaluator",
    "PassThroughPolicyEvaluator",
    "PolicyEvaluationResult",
    "ProfilePolicyEvaluator",
    "ProviderRoute",
    "REGISTRY",
    "RiskClass",
    "RedirectPolicy",
    "ScopeSnapshot",
    "ScopePolicy",
    "ScopeRequirement",
    "SideEffectClass",
    "Success",
    "TaskPolicy",
    "TargetEnvelope",
    "TargetSelector",
    "TrafficDestination",
    "UnavailableCapability",
    "ValidationFailure",
    "legacy_payload_signals_error",
    "make_input_model",
    "make_json_object_output_model",
    "outcome_from_mcp_error",
    "success_from_legacy_payload",
]
