# Copyright 2026 Javier Roldán Ortiz
# SPDX-License-Identifier: Apache-2.0

"""Implementation-audited maximum effects for every canonical action.

This module is deliberately data-only so the inventory generator can load it
without importing the Registry.  Each action is assigned exactly once to a
fully specified effect contract.  The group notes explain intentional maximum
supersets, such as optional ingestion or refresh branches.
"""

from __future__ import annotations

from typing import Any


_GROUPS: tuple[dict[str, Any], ...] = (
    {
        "name": "pure_local_read",
        "effects": {
            "traffic": [],
            "localWrites": [],
            "localChange": False,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "pure_read",
        },
        "auditNote": "Implementation reads local/public metadata only and has no write, provider, credential, or job-control branch.",
        "actions": (
            "jobs.list", "adapters.list", "adapters.capabilities",
            "documentation.list_templates", "documentation.list_layers",
            "documentation.build_report_context", "documentation.build_finding_draft",
            "documentation.summarize_coverage", "scope.check_target",
            "workspace.prepare_target_context", "workspace.summary",
            "credentials.list", "credentials.browser_auth_check_setup", "credentials.get",
            "dumps.list", "cache.inspect_scope_data", "cache.inspect_generated_artifacts",
            "xss.generate_test_code", "spec_import.capabilities",
            "headers_cookies.capabilities", "jwt.capabilities", "csrf.capabilities",
            "csrf.generate_test_plan", "cors.capabilities", "cors.generate_test_plan",
            "insecure_deser.capabilities", "xxe.capabilities", "xxe.generate_test_plan",
            "graphql.capabilities", "graphql.generate_test_plan", "tls_posture.capabilities",
            "ssrf.generate_test_plan", "open_redirect.generate_test_plan",
            "command_injection.generate_test_plan", "command_injection.prepare_replay",
            "cve.capabilities", "cve.sources", "cve.session_key.status", "cve.plan_tests",
            "cve.prepare_replay", "ssti.capabilities", "ssti.plan_tests", "ssti.prepare_replay",
            "lfi.capabilities", "lfi.plan_tests", "ssi.capabilities", "ssi.plan_tests",
            "ssi.prepare_replay", "access_control.capabilities", "access_control.plan_tests",
            "js.capabilities", "ffuf.profiles", "nuclei.profiles", "nmap.profiles",
            "shodan.session_key.status", "shodan.company_queries", "evidence.tail",
            "evidence.host_context", "fingerprint.read_host",
        ),
    },
    {
        "name": "job_status_refresh",
        "effects": {
            "traffic": [],
            "localWrites": ["workspace", "evidence", "jobs", "reports_artifacts"],
            "localChange": True,
            "localDestruction": True,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "A status read may finalize a worker, ingest its result, update workspace/evidence/job state, and remove process sidecars; finalized sidecar-free jobs resolve to an effective pure read.",
        "actions": ("jobs.status",),
    },
    {
        "name": "sensitive_local_read",
        "effects": {
            "traffic": [],
            "localWrites": [],
            "localChange": False,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": True,
            "secretUse": True,
            "replaySafety": "pure_read",
        },
        "auditNote": "The optional detailed branch resolves protected credential/evidence material but does not write or send traffic.",
        "actions": (
            "documentation.build_finding_context", "documentation.build_evidence_pack",
        ),
    },
    {
        "name": "supplied_secret_local_analysis",
        "effects": {
            "traffic": [],
            "localWrites": [],
            "localChange": False,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": True,
            "replaySafety": "pure_read",
        },
        "auditNote": "The implementation analyzes caller-supplied token/secret material in memory and neither persists it nor sends traffic.",
        "actions": ("jwt.analyze",),
    },
    {
        "name": "refreshable_workspace_analysis",
        "effects": {
            "traffic": [],
            "localWrites": ["workspace", "evidence"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "Maximum includes optional/default normalization, reconciliation, refresh, and evidence-event branches; no network route is reachable.",
        "actions": (
            "perimeter.analyze_workspace", "perimeter.build_summary",
            "documentation.build_layer_report_context", "documentation.build_workspace_report_context",
            "sqli.analyze_workspace", "sqli.analyze_dump", "xss.analyze_workspace",
            "xss.analyze_dump", "csrf.analyze_workspace", "cors.analyze_workspace",
            "insecure_deser.analyze_workspace", "xxe.analyze_workspace",
            "graphql.analyze_workspace", "tls_posture.analyze_workspace",
            "headers_cookies.analyze_workspace", "ssrf.analyze_workspace",
            "open_redirect.analyze_workspace", "command_injection.analyze_workspace",
            "ssti.passive_analyze", "lfi.passive_analyze", "ssi.passive_analyze",
            "access_control.identify_objects", "access_control.build_test_matrix",
            "fingerprint.analyze_workspace",
        ),
    },
    {
        "name": "workspace_plan_cache_write",
        "effects": {
            "traffic": [],
            "localWrites": ["workspace", "reports_artifacts"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "idempotent_write",
        },
        "auditNote": "The planner persists a deterministic workspace-owned manifest or resumable queue snapshot.",
        "actions": ("documentation.plan_scope_groups", "documentation.prepare_validation_batch"),
    },
    {
        "name": "report_artifact_write",
        "effects": {
            "traffic": [],
            "localWrites": ["workspace", "evidence", "reports_artifacts"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "idempotent_write",
        },
        "auditNote": "Renderer may refresh workspace-owned layer caches, writes operator-owned report artifacts and an evidence event, and modern callers cannot authorize external destinations.",
        "actions": (
            "perimeter.render_report", "documentation.render_markdown",
            "documentation.render_layer_report", "documentation.render_workspace_report",
            "documentation.render_assessment_summary", "documentation.export_json",
        ),
    },
    {
        "name": "batched_report_artifact_write",
        "effects": {
            "traffic": [],
            "localWrites": ["workspace", "evidence", "reports_artifacts"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "The bounded report run creates run/part manifests, rendered artifacts, and an evidence event.",
        "actions": ("documentation.render_workspace_report_batches",),
    },
    {
        "name": "workspace_finding_export",
        "effects": {
            "traffic": [],
            "localWrites": ["workspace", "reports_artifacts"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "idempotent_write",
        },
        "auditNote": "Reading the finding also refreshes its workspace-owned Markdown document.",
        "actions": ("workspace.export_finding_context",),
    },
    {
        "name": "scope_configuration_write",
        "effects": {
            "traffic": [],
            "localWrites": ["workspace", "runtime_config"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "conditional",
        },
        "auditNote": "Persists global scope and, when workspaceId is supplied, the workspace-local authorization snapshot.",
        "actions": ("scope.set",),
    },
    {
        "name": "project_bootstrap_write",
        "effects": {
            "traffic": [],
            "localWrites": ["workspace", "evidence", "runtime_config", "reports_artifacts"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "Project bootstrap persists scope, workspace/evidence directories, and optional offline fingerprint artifacts.",
        "actions": ("project.start",),
    },
    {
        "name": "workspace_idempotent_write",
        "effects": {
            "traffic": [],
            "localWrites": ["workspace", "evidence"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "idempotent_write",
        },
        "auditNote": "Writes bounded workspace state and related evidence metadata; repeating the same logical update converges.",
        "actions": (
            "workspace.create", "workspace.add_target", "workspace.update_finding",
            "workspace.link_evidence_to_finding", "workspace.mark_finding_reviewed",
            "social.approve_pretext_candidate", "purple_team.mark_detection_outcome",
            "access_control.record_context", "evidence.init_project",
        ),
    },
    {
        "name": "workspace_non_idempotent_write",
        "effects": {
            "traffic": [],
            "localWrites": ["workspace", "evidence"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "Creates, appends, promotes, reconciles, or curates workspace/evidence records.",
        "actions": (
            "workspace.ingest_data", "workspace.create_finding",
            "workspace.promote_observation_to_finding", "workspace.set_entity_reportable",
            "workspace.record_candidate_validation", "workspace.curate_candidate",
            "spec_import.import_spec", "evidence.log_event",
        ),
    },
    {
        "name": "sqlmap_plan_promotion_write",
        "effects": {
            "traffic": [],
            "localWrites": ["workspace", "evidence"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "The workspace-aware branch marks selected SQLi candidates under testing and logs the lifecycle update; the generic branch remains read-only.",
        "actions": ("sqli.build_sqlmap_command",),
    },
    {
        "name": "credential_state_write",
        "effects": {
            "traffic": [],
            "localWrites": ["credentials", "evidence"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": True,
            "secretUse": True,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "Creates, replaces, or removes private credential/profile material and records only sanitized evidence metadata.",
        "actions": (
            "credentials.set", "credentials.set_auth_profile",
            "credentials.set_browser_auth_profile",
        ),
    },
    {
        "name": "credential_state_delete",
        "effects": {
            "traffic": [],
            "localWrites": ["credentials", "evidence"],
            "localChange": True,
            "localDestruction": True,
            "remoteStateChange": False,
            "credentialUse": True,
            "secretUse": True,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "Deletes private credential/profile material and records only sanitized evidence metadata; the removed secret is never returned.",
        "actions": ("credentials.delete",),
    },
    {
        "name": "runtime_secret_state_write",
        "effects": {
            "traffic": [],
            "localWrites": ["credentials"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": True,
            "secretUse": True,
            "replaySafety": "idempotent_write",
        },
        "auditNote": "Sets process-local provider secret state without persistence or traffic.",
        "actions": (
            "cve.session_key.set", "shodan.session_key.set",
        ),
    },
    {
        "name": "runtime_secret_state_clear",
        "effects": {
            "traffic": [],
            "localWrites": ["credentials"],
            "localChange": True,
            "localDestruction": True,
            "remoteStateChange": False,
            "credentialUse": True,
            "secretUse": True,
            "replaySafety": "idempotent_control",
        },
        "auditNote": "Clears process-local provider secret state without persistence or traffic.",
        "actions": ("cve.session_key.clear", "shodan.session_key.clear"),
    },
    {
        "name": "runtime_endpoint_configuration_write",
        "effects": {
            "traffic": [],
            "localWrites": ["runtime_config"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "idempotent_write",
        },
        "auditNote": "Changes an in-process provider endpoint override only; it does not contact that endpoint.",
        "actions": ("cve.set_source_endpoint", "cve.reset_source_endpoint"),
    },
    {
        "name": "credential_refresh_traffic",
        "effects": {
            "traffic": ["authorized_target"],
            "localWrites": ["credentials", "evidence"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": True,
            "credentialUse": True,
            "secretUse": True,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "Authenticates or validates against an authorized target and may replace stored session material; login methods may change remote session state.",
        "actions": ("credentials.authenticate", "credentials.validate_session"),
    },
    {
        "name": "browser_credential_refresh_job",
        "effects": {
            "traffic": ["authorized_target"],
            "localWrites": ["credentials", "evidence", "jobs", "reports_artifacts"],
            "localChange": True,
            "localDestruction": True,
            "remoteStateChange": True,
            "credentialUse": True,
            "secretUse": True,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "Browser authentication starts bounded job/process state, sends login traffic, refreshes secrets, and may clean or replace local browser/job artifacts.",
        "actions": ("credentials.browser_authenticate",),
    },
    {
        "name": "local_destructive_workspace_operation",
        "effects": {
            "traffic": [],
            "localWrites": ["workspace", "evidence", "reports_artifacts"],
            "localChange": True,
            "localDestruction": True,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "Explicitly deletes workspace, dump, evidence, or generated artifact records after operator review.",
        "actions": (
            "workspace.delete", "cache.clean_out_of_scope", "cache.clean_generated_artifacts",
        ),
    },
    {
        "name": "job_control",
        "effects": {
            "traffic": [],
            "localWrites": ["jobs"],
            "localChange": True,
            "localDestruction": True,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "idempotent_control",
        },
        "auditNote": "Cancellation mutates durable job state and may terminate a local worker process.",
        "actions": ("jobs.cancel",),
    },
    {
        "name": "local_javascript_artifact_write",
        "effects": {
            "traffic": [],
            "localWrites": ["workspace", "evidence", "reports_artifacts"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "Builds deterministic JavaScript manifests/models and logs evidence; application JavaScript is never executed and no network route is used.",
        "actions": ("js.discover_assets", "js.build_app_model", "js.render_app_map"),
    },
    {
        "name": "background_javascript_analysis",
        "effects": {
            "traffic": [],
            "localWrites": ["workspace", "evidence", "jobs", "reports_artifacts"],
            "localChange": True,
            "localDestruction": True,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "The maximum covers foreground artifacts plus optional worker/job state, replacement, timeout, and finalization cleanup.",
        "actions": ("js.analyze_static", "js.normalize_endpoints"),
    },
    {
        "name": "offline_sitemap_artifacts",
        "effects": {
            "traffic": [],
            "localWrites": ["workspace", "evidence", "reports_artifacts"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "Always writes the sitemap plus Mermaid/SVG artifacts under trusted local roots; the evidence dimension is retained as a safe maximum for legacy recordable execution. Modern input cannot authorize an external output.",
        "actions": ("sitemap.from_dump",),
    },
    {
        "name": "offline_fingerprint_artifacts",
        "effects": {
            "traffic": [],
            "localWrites": ["evidence", "reports_artifacts"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "idempotent_write",
        },
        "auditNote": "Writes organization/host fingerprint JSON, a summary artifact, and a sanitized evidence event from an offline dump.",
        "actions": ("fingerprint.from_dump",),
    },
    {
        "name": "command_builder_with_secret",
        "effects": {
            "traffic": [],
            "localWrites": ["reports_artifacts"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": True,
            "secretUse": True,
            "replaySafety": "idempotent_write",
        },
        "auditNote": "Builds but does not launch a command; optional credentials are resolved only to construct the protected execution command, and workspace-owned target/output files or directories may be created.",
        "actions": ("ffuf.build_command", "nuclei.build_command"),
    },
    {
        "name": "command_builder_without_secret",
        "effects": {
            "traffic": [],
            "localWrites": ["reports_artifacts"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "idempotent_write",
        },
        "auditNote": "Builds but does not launch a command; resolving the default workspace output may create an operator-owned directory.",
        "actions": ("nmap.build_command",),
    },
    {
        "name": "active_target_probe_with_credentials",
        "effects": {
            "traffic": ["authorized_target"],
            "localWrites": ["workspace", "evidence"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": True,
            "credentialUse": True,
            "secretUse": True,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "Maximum covers optional authenticated target traffic, evidence/normalization writes, and methods whose endpoint semantics may mutate remote state.",
        "actions": (
            "xss.execute_test", "cors.execute_test", "xxe.execute_test",
            "graphql.execute_test", "ssrf.execute_test", "open_redirect.execute_test",
            "command_injection.execute_test", "cve.execute_test", "ssti.execute_test",
            "lfi.execute_test", "ssi.execute_test", "access_control.execute_matrix_test",
        ),
    },
    {
        "name": "javascript_asset_fetch",
        "effects": {
            "traffic": ["authorized_target"],
            "localWrites": ["workspace", "evidence", "reports_artifacts"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": True,
            "secretUse": True,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "Fetches bounded GET-only assets, stores workspace artifacts/evidence, and may resolve an optional scoped credential; it does not execute JavaScript.",
        "actions": ("js.fetch_assets",),
    },
    {
        "name": "version_get_probe",
        "effects": {
            "traffic": ["authorized_target"],
            "localWrites": ["workspace", "evidence"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "Sends bounded benign GET requests and records/enriches local evidence; the implementation has no credential or state-changing method branch.",
        "actions": ("fingerprint.probe_versions",),
    },
    {
        "name": "background_active_scan_with_credentials",
        "effects": {
            "traffic": ["authorized_target"],
            "localWrites": ["workspace", "evidence", "jobs", "reports_artifacts"],
            "localChange": True,
            "localDestruction": True,
            "remoteStateChange": True,
            "credentialUse": True,
            "secretUse": True,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "Maximum covers scanner/crawler target traffic, optional credentials, workspace/evidence ingestion, artifacts, worker state, overwrite/prune, cancellation, and state-changing crawl methods.",
        "actions": (
            "crawler.crawl", "crawler.extended", "ffuf.run_profile", "nuclei.run_profile",
        ),
    },
    {
        "name": "background_active_scan_without_credentials",
        "effects": {
            "traffic": ["authorized_target"],
            "localWrites": ["workspace", "evidence", "jobs", "reports_artifacts"],
            "localChange": True,
            "localDestruction": True,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "Nmap launches a bounded local scanner, writes job/output/evidence state, and sends target traffic without a credential or application-state mutation contract.",
        "actions": ("nmap.run_profile",),
    },
    {
        "name": "third_party_cve_correlation",
        "effects": {
            "traffic": ["third_party"],
            "localWrites": ["workspace", "evidence"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": True,
            "secretUse": True,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "Queries configured public intelligence providers, optionally uses runtime provider keys, and reconciles candidate/evidence state; it sends no target identity or traffic.",
        "actions": ("cve.correlate",),
    },
    {
        "name": "third_party_shodan_api_read",
        "effects": {
            "traffic": ["third_party"],
            "localWrites": ["workspace", "evidence"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": True,
            "secretUse": True,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "Calls the Shodan API with the process-local key, records a sanitized evidence event, and may normalize results into workspace state.",
        "actions": (
            "shodan.host", "shodan.domain", "shodan.resolve", "shodan.reverse",
            "shodan.search_count", "shodan.search", "shodan.search_facets",
            "shodan.search_filters", "shodan.target_summary",
        ),
    },
    {
        "name": "third_party_keyless_intelligence_read",
        "effects": {
            "traffic": ["third_party"],
            "localWrites": ["workspace", "evidence"],
            "localChange": True,
            "localDestruction": False,
            "remoteStateChange": False,
            "credentialUse": False,
            "secretUse": False,
            "replaySafety": "non_idempotent",
        },
        "auditNote": "Calls the keyless InternetDB provider, records evidence, and may ingest normalized host intelligence.",
        "actions": ("shodan.internetdb",),
    },
)


def build_effect_declarations() -> dict[str, dict[str, Any]]:
    """Return a fresh action-id keyed copy and fail on duplicate declarations."""

    declarations: dict[str, dict[str, Any]] = {}
    for group in _GROUPS:
        effects = dict(group["effects"])
        required = {
            "traffic", "localWrites", "localChange", "localDestruction",
            "remoteStateChange", "credentialUse", "secretUse", "replaySafety",
        }
        if set(effects) != required:
            raise RuntimeError(f"effect group {group['name']} does not explicitly declare every dimension")
        for action_id in group["actions"]:
            if action_id in declarations:
                raise RuntimeError(f"duplicate effect declaration: {action_id}")
            declarations[action_id] = {
                **effects,
                "auditGroup": group["name"],
                "auditNote": group["auditNote"],
            }
    if len(declarations) != 174:
        raise RuntimeError(f"expected 174 effect declarations, found {len(declarations)}")
    return declarations


EFFECT_DECLARATIONS = build_effect_declarations()
