# Copyright 2026 Javier Roldán Ortiz
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import base64
from functools import lru_cache
from typing import Any

from ... import __version__ as SYNAPSE_VERSION
from ..paths import SYNAPSE_ROOT


REPORT_BANNER_PATH = SYNAPSE_ROOT / "assets" / "Offensive-Synapse-Banner-Report.jpg"
BANNER_PATH = SYNAPSE_ROOT / "assets" / "Offensive-Synapse-Banner.png"
# The report hero uses the darker, blue-toned "docs" brand banner (optimized JPEG),
# which sits more harmonically over the navy report body than the red console banner.
DOCS_BANNER_PATH = SYNAPSE_ROOT / "assets" / "Synapse-Docs-Banner.jpg"
MODE_TOGGLE_SCRIPT = (
    "function setMode(mode){var high=mode==='high-level';document.body.classList.toggle('operator',!high);"
    "document.body.classList.toggle('high-level',high);var op=document.getElementById('btnOp');var hi=document.getElementById('btnHigh');"
    "if(op){op.setAttribute('aria-pressed',String(!high));}if(hi){hi.setAttribute('aria-pressed',String(high));}"
    "var name=document.getElementById('reportName');if(name){name.textContent=high?'High-Level Report':'Operator Report';}"
    "var badge=document.getElementById('modeBadge');if(badge){badge.textContent=high?'Internal Summary':'Internal Operational Report';}"
    "var bn=document.getElementById('bannerNote');if(bn){var l=bn.querySelector('.line');var s=bn.querySelector('.sub');if(l){l.textContent=high?'internal summary':'internal operator report';}if(s){s.textContent=high?'not a client deliverable \\u00b7 reduced operational noise':'not a client deliverable \\u00b7 contains live values';}}"
    "var note=document.getElementById('footNote');if(note){note.textContent=high?'High-level view - internal summary with reduced operational noise. Source of truth: workspace state and evidence.':'Operator report - internal references included. Source of truth: workspace state and evidence.';}}"
)


@lru_cache(maxsize=1)
def banner_data_uri() -> str:
    for path, mime_type in ((REPORT_BANNER_PATH, "image/jpeg"), (BANNER_PATH, "image/png")):
        try:
            data = path.read_bytes()
        except OSError:
            continue
        return f"data:{mime_type};base64," + base64.b64encode(data).decode("ascii")
    return ""


@lru_cache(maxsize=1)
def docs_banner_data_uri() -> str:
    for path, mime_type in ((DOCS_BANNER_PATH, "image/jpeg"), (REPORT_BANNER_PATH, "image/jpeg"), (BANNER_PATH, "image/png")):
        try:
            data = path.read_bytes()
        except OSError:
            continue
        return f"data:{mime_type};base64," + base64.b64encode(data).decode("ascii")
    return ""


def html_shell(title: Any, body: str, script: str = "", meta: dict[str, Any] | None = None, body_class: str = "operator") -> str:
    combined_script = MODE_TOGGLE_SCRIPT + script
    script_html = f"<script>{combined_script}</script>" if combined_script.strip() else ""
    footer_bits = ["Generated by Synapse"]
    footer_meta = meta or {}
    footer_bits.append(f"v{SYNAPSE_VERSION}")
    if footer_meta.get("workspace"):
        footer_bits.append(f"workspace {footer_meta['workspace']}")
    if footer_meta.get("generated"):
        footer_bits.append(str(footer_meta["generated"]))
    footer_bits.append("authorized engagement use only")
    footer_text = escape_text(" - ".join(footer_bits))
    return (
        "<!doctype html>\n<html><head><meta charset=\"utf-8\">"
        "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
        f"<title>{escape_text(title)}</title>"
        f"<style>{report_css()}</style>"
        f"{script_html}"
        f"</head><body class=\"{escape_text(body_class)}\">"
        "<!-- CSS hiding in this report is only for internal presentation-density switching. "
        "It is not a security or client-deliverable redaction mechanism. -->"
        f"{body}"
        f'<footer class="synapse-report-footer"><span class="mono">{footer_text}</span>'
        '<span class="footer-note" id="footNote">Operator report - internal references included. '
        "Source of truth: workspace state and evidence.</span></footer>"
        "</body></html>\n"
    )


def banner_html(title: Any, subtitle: Any = "", meta: dict[str, Any] | None = None) -> str:
    meta_items = []
    for key, value in (meta or {}).items():
        if value in ("", None, [], {}):
            continue
        rendered_value = '<span id="reportName">Operator Report</span>' if str(key).lower() == "report" else escape_text(value)
        meta_items.append(f"<span><strong>{escape_label(key)}</strong> {rendered_value}</span>")
    meta_html = "".join(meta_items)
    return (
        '<header class="banner">'
        f'<img class="banner-art" src="{docs_banner_data_uri()}" alt="Synapse - the agentic operations layer for offensive security">'
        '<div class="banner-fade" aria-hidden="true"></div>'
        '<div class="banner-note" id="bannerNote"><span class="line">internal operator report</span>'
        '<span class="sub">not a client deliverable &middot; contains live values</span></div>'
        "</header>"
        '<div class="meta">'
        f"{meta_html}"
        '<span class="spacer"></span>'
        '<span class="mode-badge" id="modeBadge">Internal Operational Report</span>'
        '<div class="switch" role="group" aria-label="Report view">'
        '<button id="btnOp" type="button" aria-pressed="true" onclick="setMode(\'operator\')">Operator</button>'
        '<button id="btnHigh" type="button" aria-pressed="false" onclick="setMode(\'high-level\')">High-Level</button>'
        "</div></div>"
    )


def report_css() -> str:
    return (
        # --- Design tokens (shared) ---------------------------------------------------
        # Palette ("Indigo"): a deep indigo-navy field (--bg ladder) with a single vivid
        # azure structural accent (--accent) and warm ember (--red) reserved for
        # danger/severity signal. Frames are kept flat and low-contrast so panels mix
        # into the field rather than stand proud.
        ":root{--bg:#070b14;--bg-elev:#0c1120;--bg-elev-2:#11182b;--line:#1d2740;--line-soft:#161e30;"
        "--ink:#e9edf8;--ink-dim:#9aa5c0;--ink-faint:#626d8a;--accent:#5aa6ec;--accent-deep:#3d76b4;--blue:#74b8f2;--blue-deep:#4a8ccc;--red:#ec6055;--green:#56c08e;--amber:#e3a948;"
        "--sev-crit:#ec6055;--sev-high:#ec6055;--sev-med:#e3a948;--sev-low:#74b8f2;--sev-info:#626d8a;--r:12px;--maxw:1680px;"
        # Operator opted into design fonts; system stacks remain as offline fallback.
        "--display:'Oxanium',system-ui,-apple-system,\"Segoe UI\",Roboto,sans-serif;--body:'IBM Plex Sans',system-ui,-apple-system,\"Segoe UI\",Roboto,sans-serif;"
        "--mono:'JetBrains Mono',ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}"
        "*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(1200px 520px at 50% -10%,rgba(90,166,236,.06),transparent 60%),var(--bg);background-attachment:fixed;color:var(--ink);font-family:var(--body);font-size:14px;line-height:1.62;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility;font-variant-numeric:tabular-nums}"
        ".wrap{width:100%;max-width:var(--maxw);margin:0 auto;padding:0 32px 96px}.report-strip{width:calc(100% - 64px);max-width:calc(var(--maxw) - 64px);margin:24px auto 0;padding:0}a{color:var(--ink);text-decoration:none}::selection{background:rgba(90,166,236,.28)}"
        # --- Banner -------------------------------------------------------------------
        ".banner{position:relative;width:100%;margin:0;overflow:hidden;border-bottom:1px solid var(--line);background:var(--bg)}.banner-art{display:block;width:100%;height:auto;max-height:clamp(168px,23vw,300px);object-fit:cover;object-position:center}.banner-fade{position:absolute;left:0;right:0;bottom:0;height:84px;background:linear-gradient(to bottom,transparent,var(--bg));pointer-events:none}"
        ".banner-note{position:absolute;right:28px;bottom:16px;z-index:3;display:flex;flex-direction:column;gap:2px;text-align:right;line-height:1.5;font-family:var(--mono);text-shadow:0 1px 10px rgba(0,0,0,.65)}.banner-note .line{font-size:10.5px;color:var(--ink-dim);text-transform:uppercase;letter-spacing:.16em}.banner-note .sub{font-size:10px;color:var(--ink-faint)}body.high-level .banner-note .line{color:var(--blue)}"
        # --- Meta bar + view switch ---------------------------------------------------
        ".meta{width:calc(100% - 64px);max-width:calc(var(--maxw) - 64px);display:flex;flex-wrap:wrap;align-items:center;gap:14px 28px;margin:18px auto 0;padding:17px 20px;background:var(--bg-elev);border:1px solid var(--line);border-radius:var(--r)}.meta span:not(.spacer):not(.mode-badge){display:flex;flex-direction:column;gap:3px}.meta strong{font-family:var(--mono);font-size:10px;letter-spacing:.14em;text-transform:uppercase;color:var(--ink-faint);font-weight:500}.meta span{font-size:14px;color:var(--ink);font-weight:500}.meta .spacer{flex:1 1 auto}.mode-badge{font-family:var(--display);font-weight:600;letter-spacing:.06em;font-size:12px;text-transform:uppercase;padding:7px 13px;border-radius:999px;border:1px solid var(--accent);color:var(--accent);background:rgba(90,166,236,.08)}body.high-level .mode-badge{border-color:var(--blue);color:var(--blue);background:rgba(87,174,222,.08)}"
        ".switch{display:inline-flex;border:1px solid var(--line);border-radius:999px;padding:3px;background:var(--bg)}.switch button{font-family:var(--display);font-size:12px;font-weight:600;letter-spacing:.05em;text-transform:uppercase;color:var(--ink-dim);background:transparent;border:0;padding:7px 14px;border-radius:999px;cursor:pointer;transition:color .18s}.switch button[aria-pressed=\"true\"]{background:var(--accent);color:#06222a}body.high-level .switch button[aria-pressed=\"true\"]{background:var(--blue);color:#06222a}"
        # --- Risk posture + finding cards --------------------------------------------
        ".section-label{display:flex;align-items:center;gap:9px;font-family:var(--mono);font-weight:500;font-size:12px;letter-spacing:.14em;text-transform:uppercase;color:var(--accent);margin:0}.section-label:before{content:\"\";width:7px;height:7px;border-radius:50%;background:var(--accent)}"
        ".risk-panel{position:relative;background:var(--bg-elev);border:1px solid var(--line);border-radius:var(--r);padding:22px 24px 24px;overflow:hidden}.risk-top{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;margin-bottom:18px}.risk-top p{margin:8px 0 0;color:var(--ink-dim);font-family:var(--mono);font-size:12px}.risk-tiles{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.risk-tile{position:relative;background:var(--bg-elev-2);border:1px solid var(--line);border-radius:10px;padding:15px 16px;overflow:hidden}.risk-num{display:block;font-family:var(--display);font-weight:800;font-size:36px;line-height:1;color:var(--ink-faint)}.risk-label{display:flex;align-items:center;gap:7px;margin-top:9px;font-family:var(--mono);font-size:11px;letter-spacing:.05em;text-transform:uppercase;color:var(--ink-faint)}.risk-label:before{content:\"\";width:7px;height:7px;border-radius:50%;background:currentColor}.severity-critical .risk-num,.severity-critical.risk-driver b{color:var(--sev-crit)}.severity-high .risk-num,.severity-high.risk-driver b{color:var(--sev-crit)}.severity-medium .risk-num,.severity-medium.risk-driver b{color:var(--sev-med)}.severity-low .risk-num,.severity-low.risk-driver b{color:var(--sev-low)}.risk-drivers{display:flex;gap:10px 22px;flex-wrap:wrap;margin-top:18px;padding-top:16px;border-top:1px solid var(--line-soft)}.risk-driver{display:flex;align-items:center;gap:8px;font-size:12.5px;color:var(--ink-dim)}.risk-driver:before{content:\"\";width:8px;height:8px;border-radius:2px;background:var(--blue)}.risk-driver.severity-high:before,.risk-driver.severity-critical:before{background:var(--red)}.risk-driver.severity-medium:before{background:var(--sev-med)}.risk-driver em{font-style:normal;color:var(--ink-faint)}.risk-tile.is-zero .risk-num{color:var(--ink-faint)}"
        ".finding-strip{margin-top:30px}.finding-strip>.section-label{margin-bottom:12px}.finding-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(340px,1fr));gap:16px}.finding-card{background:var(--bg-elev);border:1px solid var(--line);border-left:3px solid var(--red);border-radius:10px;padding:18px 20px}.finding-card-top{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:10px}.finding-card h4{font-size:15.5px;font-weight:650;margin:0 0 8px;color:#f4f7fb;overflow-wrap:anywhere}.finding-card p{margin:0 0 10px;color:var(--ink-dim)}.finding-ref{font-family:var(--mono);font-size:11.5px;color:var(--ink-faint);overflow-wrap:anywhere}"
        # --- Layout + table of contents ----------------------------------------------
        ".layout{display:grid;grid-template-columns:minmax(210px,260px) minmax(0,1fr);gap:44px;margin-top:40px}.report-toc{position:sticky;top:24px;align-self:start;max-height:calc(100vh - 48px);overflow:auto;border:0;background:transparent;padding:0 8px 8px 0;box-shadow:none;z-index:3}.report-toc h2{font-family:var(--mono);font-size:10px;letter-spacing:.18em;text-transform:uppercase;color:var(--ink-faint);margin:0 0 14px 18px;border:0;padding:0}.report-toc ol{list-style:none;margin:0;padding:0;position:relative}.report-toc ol:before{content:\"\";position:absolute;left:5px;top:6px;bottom:6px;width:1px;background:var(--line)}.report-toc li{position:relative;padding:6px 0 6px 20px}.report-toc li:before{content:\"\";position:absolute;left:1px;top:13px;width:9px;height:9px;border-radius:50%;background:var(--bg);border:1.5px solid var(--ink-faint);transition:.18s}.report-toc a{display:block;color:var(--ink-dim);font-size:13.5px;line-height:1.35;transition:.15s;overflow-wrap:anywhere;border-radius:6px;padding:2px 6px;margin-left:-6px}.report-toc a:hover,.report-toc a.active{color:var(--ink);background:rgba(90,166,236,.1)}.report-toc li:hover:before,.report-toc li:has(a.active):before{border-color:var(--accent);box-shadow:0 0 0 3px rgba(90,166,236,.16)}"
        # High-level dossier: the index becomes a flat left-ruled list, not a node timeline.
        "body.high-level .report-toc ol:before{display:none}body.high-level .report-toc li{padding-left:0}body.high-level .report-toc li:before{display:none}body.high-level .report-toc a{border-left:2px solid var(--line);border-radius:0;padding:6px 0 6px 13px;margin-left:0}body.high-level .report-toc a:hover,body.high-level .report-toc a.active{border-left-color:var(--accent);background:transparent;color:var(--ink)}"
        # --- Layers -------------------------------------------------------------------
        ".synapse-report-main{min-width:0;overflow:hidden}.layer{margin-bottom:56px;scroll-margin-top:20px}.layer:target,.block:target{outline:1px solid rgba(90,166,236,.4);outline-offset:10px;border-radius:var(--r)}.layer-head{display:flex;align-items:baseline;gap:14px;padding-bottom:14px;border-bottom:1px solid var(--line);margin-bottom:8px}.layer-head .idx{font-family:var(--mono);font-size:13px;font-weight:600;letter-spacing:.08em;color:var(--accent)}.layer-head h2{font-family:var(--display);font-weight:700;letter-spacing:.01em;font-size:24px;text-transform:uppercase;margin:0;color:#f4f6fa}.layer-head .sub{margin-left:auto;font-family:var(--mono);font-size:12px;color:var(--ink-faint);text-transform:uppercase;letter-spacing:.06em}"
        # High-level dossier: oversized hollow section numerals, editorial title.
        "body.high-level .layer-head{align-items:flex-end;gap:22px;border-bottom:2px solid var(--line)}body.high-level .layer-head .idx{font-family:var(--display);font-weight:800;font-size:clamp(46px,7vw,84px);line-height:.74;color:transparent;-webkit-text-stroke:1.5px var(--accent);letter-spacing:.02em}body.high-level .layer-head h2{font-family:var(--body);font-weight:600;text-transform:none;font-size:clamp(22px,2.6vw,30px);letter-spacing:-.01em}"
        # --- Blocks, stats, lists -----------------------------------------------------
        ".block{margin-top:26px}.block>h2,.block>h3,.block>h4{font-family:var(--mono);font-weight:500;font-size:12px;letter-spacing:.1em;text-transform:uppercase;color:var(--ink-dim);margin:0 0 12px;display:flex;align-items:center;gap:9px}.block>h2:before,.block>h3:before,.block>h4:before{content:\"\";width:6px;height:6px;border-radius:50%;background:var(--accent)}p{margin:8px 0 12px;color:var(--ink-dim)}"
        ".summary-block{margin:8px 0 12px}.layer-highlights{margin:0 0 18px;padding-left:18px;color:var(--ink-dim)}.layer-highlights li{margin:5px 0}.target-block{padding-top:18px;border-top:1px solid var(--line-soft)}.layer-brief{margin-top:22px}.operator-detail{margin-top:22px;border:1px solid var(--line);border-radius:10px;background:var(--bg-elev);overflow:hidden}.operator-detail>summary{cursor:pointer;list-style:none;padding:14px 18px;font-family:var(--mono);font-size:11px;letter-spacing:.12em;text-transform:uppercase;color:var(--ink-dim);display:flex;align-items:center;gap:10px}.operator-detail>summary::-webkit-details-marker{display:none}.operator-detail>summary:before{content:\"+\";font-family:var(--display);font-weight:700;color:var(--accent);font-size:15px}.operator-detail[open]>summary:before{content:\"-\"}.operator-detail>summary span{margin-left:auto;color:var(--ink-faint);letter-spacing:.04em}.operator-detail[open]>summary{border-bottom:1px solid var(--line)}.operator-detail-body{padding:0 18px 20px}.stat-grid,.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:14px;margin:8px 0 10px}.stat-card,.card{position:relative;background:var(--bg-elev);border:1px solid var(--line);border-radius:var(--r);padding:16px 18px;overflow:hidden}.stat-value,.card .n{display:block;font-family:var(--display);font-weight:800;font-size:30px;line-height:1;letter-spacing:-.01em;font-variant-numeric:tabular-nums;color:#f4f6fa}.stat-label,.card .l{display:block;margin-top:8px;font-family:var(--mono);font-size:11px;letter-spacing:.05em;color:var(--ink-faint);text-transform:uppercase}.summary-list{margin-top:6px}.summary-list li strong{color:var(--ink)}"
        # High-level dossier: stat cells flatten into a ruled grid.
        "body.high-level .stat-grid,body.high-level .cards{gap:0;border-top:1px solid var(--line);border-left:1px solid var(--line)}body.high-level .stat-card,body.high-level .card{background:transparent;border:0;border-right:1px solid var(--line);border-bottom:1px solid var(--line);border-radius:0}body.high-level .stat-card:before{display:none}"
        "ul{margin:8px 0 0;padding-left:20px}li{margin:4px 0}.table-wrap{width:100%;max-width:100%;overflow-x:auto;overflow-y:hidden;border:1px solid var(--line);border-radius:var(--r);background:var(--bg-elev)}table{border-collapse:collapse;width:100%;min-width:0;table-layout:fixed;font-size:13.5px;background:transparent}thead th{text-align:left;font-family:var(--mono);font-weight:500;font-size:10.5px;letter-spacing:.08em;text-transform:uppercase;color:var(--ink-dim);padding:11px 14px;background:var(--bg-elev-2);border-bottom:1px solid var(--line);white-space:normal;overflow-wrap:anywhere}tbody td{padding:11px 14px;border-bottom:1px solid var(--line-soft);color:var(--ink);vertical-align:top;overflow-wrap:anywhere;word-break:break-word}tbody tr:last-child td{border-bottom:0}tbody tr:hover td{background:rgba(90,166,236,.05)}code,.mono{font-family:var(--mono);font-size:12.5px;color:var(--ink-dim)}code{word-break:break-word;background:#0c1f25;border:1px solid var(--line);border-radius:4px;padding:1px 4px}"
        # High-level dossier: flatter tables (hairline top rule, no panel).
        "body.high-level .table-wrap{border:0;border-top:1px solid var(--line);border-radius:0;background:transparent}body.high-level thead th{background:transparent;color:var(--ink-faint)}"
        # --- View toggle + controls ---------------------------------------------------
        "body.high-level .operator-only{display:none!important}body.operator .high-level-only{display:none!important}body.single-target .host-column,body.single-target .host-label{display:none!important}.controls{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:8px 0 12px}.controls input{font-family:var(--mono);padding:7px 9px;border:1px solid var(--line);border-radius:4px;min-width:280px;background:var(--bg);color:var(--ink)}.controls button{font-family:var(--mono);padding:7px 10px;border:1px solid var(--line);border-radius:4px;background:var(--bg-elev-2);color:var(--ink);cursor:pointer}.tree details{margin-left:18px}.tree summary{cursor:pointer;padding:3px 0;color:var(--ink)}.record,.request{display:grid;grid-template-columns:70px 92px minmax(240px,1.3fr) minmax(130px,.7fr) minmax(180px,1fr);gap:8px;align-items:start;margin:4px 0 4px 28px;padding:6px 8px;border-left:3px solid var(--accent);background:var(--bg-elev);font-size:13px}.request.js{border-left-color:var(--blue);background:rgba(87,174,222,.06)}.request.observed{border-left-color:#7fb8c0}.signal-tree details{margin-left:0}.signal-record{grid-template-columns:minmax(180px,.8fr) minmax(220px,1.1fr) minmax(220px,1fr) minmax(180px,1fr);border-left-color:var(--accent)}body.single-target .signal-record{grid-template-columns:minmax(220px,1.1fr) minmax(220px,1fr) minmax(180px,1fr)}body.single-target .signal-record>span:first-child{display:none!important}"
        # --- Badges -------------------------------------------------------------------
        ".badge{display:inline-flex;align-items:center;gap:6px;font-family:var(--display);font-weight:700;font-size:10px;letter-spacing:.05em;text-transform:uppercase;padding:3px 9px;border-radius:6px;border:1px solid var(--line);white-space:nowrap;color:var(--ink-dim);background:var(--bg-elev-2)}.badge:before{content:\"\";width:6px;height:6px;border-radius:50%;background:currentColor}.badge-critical,.badge-high{color:var(--sev-crit);border-color:rgba(239,90,79,.5);background:rgba(239,90,79,.1)}.badge-medium{color:var(--sev-med);border-color:rgba(230,173,69,.5);background:rgba(230,173,69,.1)}.badge-low{color:var(--sev-low);border-color:rgba(87,174,222,.5);background:rgba(87,174,222,.1)}.badge-info{color:var(--ink-faint);border-color:var(--line);background:transparent}.badge-ok{color:var(--green);border-color:rgba(92,197,150,.5);background:rgba(92,197,150,.1)}.muted{color:var(--ink-faint)}"
        # High-level dossier: badges read as inline text markers, not filled chips.
        "body.high-level .badge{background:transparent;border-color:transparent;padding:3px 0;font-weight:700}"
        # --- Empty state + findings + candidate groups --------------------------------
        ".empty-state,.empty{display:flex;align-items:center;gap:12px;padding:16px 18px;background:var(--bg-elev);border:1px dashed var(--line);border-radius:var(--r);color:var(--ink-faint);font-style:italic;font-size:13.5px}.empty-state:before,.empty:before{content:\"\";flex:0 0 auto;width:8px;height:8px;border-radius:50%;border:1.5px solid var(--ink-faint)}.finding{border:1px solid var(--line);border-left:3px solid var(--red);border-radius:var(--r);background:var(--bg-elev);padding:18px 20px;margin-top:14px}.finding h4{font-family:var(--display);font-size:16px;font-weight:700;margin:0 0 4px;color:#f4f6fa;overflow-wrap:anywhere;word-break:break-word}.finding .ftop{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:10px}.finding p{margin:8px 0 0;color:var(--ink-dim);font-size:13.5px;overflow-wrap:anywhere;word-break:break-word}.finding .ref{font-family:var(--mono);font-size:12px;color:var(--ink-faint)}.candidate-group{margin-top:18px}.candidate-group:first-child{margin-top:0}.candidate-group-title{display:flex;align-items:center;gap:11px;font-family:var(--display);font-size:12.5px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:var(--ink);margin:0 0 9px}.candidate-group-title .muted{font-family:var(--mono);font-size:10.5px;font-weight:500;letter-spacing:.02em;text-transform:none;color:var(--accent);border:1px solid rgba(90,166,236,.42);background:rgba(90,166,236,.08);padding:2px 9px;border-radius:999px;white-space:nowrap}"
        ".next-step-list{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:10px}.next-step-list li{display:flex;gap:14px;align-items:flex-start;background:var(--bg-elev);border:1px solid var(--line);border-left:2px solid var(--accent);border-radius:10px;padding:14px 18px}.step-num{flex:0 0 auto;font-family:var(--display);font-weight:700;font-size:14px;color:var(--accent);min-width:22px}"
        # --- Executive summary (high-level view) --------------------------------------
        # The high-level view is its own stakeholder one-pager, not a stripped operator
        # console: editorial single column, plain-language findings, themed concern areas.
        ".exec-summary{max-width:1040px;margin:36px auto 0;padding:0 32px 8px}body.high-level .risk-drivers{display:none}.exec-eyebrow{display:block;font-family:var(--mono);font-size:11px;letter-spacing:.26em;text-transform:uppercase;color:var(--accent)}.exec-headline{font-family:var(--body);font-weight:600;font-size:clamp(23px,2.8vw,32px);line-height:1.28;letter-spacing:-.01em;color:#f4f7fb;margin:14px 0 0;max-width:34ch}.exec-sub{font-family:var(--mono);font-size:12px;line-height:1.7;color:var(--ink-faint);margin:14px 0 0;max-width:78ch}"
        ".exec-block{margin-top:38px}.exec-label{font-family:var(--mono);font-size:11px;letter-spacing:.2em;text-transform:uppercase;color:var(--ink-dim);margin:0;padding-bottom:12px;border-bottom:1px solid var(--line)}.exec-empty{color:var(--ink-faint);font-style:italic;margin:14px 0 0}"
        ".exec-findings{list-style:none;margin:0;padding:0}.exec-findings li{display:flex;gap:16px;align-items:baseline;padding:16px 0;border-bottom:1px solid var(--line-soft)}.exec-findings li:last-child{border-bottom:0}.exec-finding-body{min-width:0}.exec-findings b{display:block;font-family:var(--body);font-weight:600;font-size:16px;color:#f4f7fb;overflow-wrap:anywhere}.exec-asset{display:block;margin-top:4px;font-family:var(--mono);font-size:12px;color:var(--ink-faint);overflow-wrap:anywhere}"
        ".exec-themes{list-style:none;margin:0;padding:0}.exec-themes li{display:flex;align-items:center;gap:14px;padding:14px 0;border-bottom:1px solid var(--line-soft)}.exec-themes li:last-child{border-bottom:0}.exec-themes b{font-family:var(--body);font-weight:500;font-size:15px;color:var(--ink)}.exec-dot{flex:0 0 auto;width:9px;height:9px;border-radius:2px;background:var(--ink-faint)}.exec-dot.severity-critical,.exec-dot.severity-high{background:var(--red)}.exec-dot.severity-medium{background:var(--amber)}.exec-dot.severity-low{background:var(--blue)}.exec-theme-meta{margin-left:auto;font-family:var(--mono);font-size:12px;color:var(--ink-faint);white-space:nowrap}"
        ".exec-actions{list-style:none;margin:0;padding:0}.exec-actions li{display:flex;gap:16px;align-items:flex-start;padding:15px 0;border-bottom:1px solid var(--line-soft);color:var(--ink-dim);line-height:1.6}.exec-actions li:last-child{border-bottom:0}.exec-actions .num{flex:0 0 auto;font-family:var(--display);font-weight:700;color:var(--accent);font-size:15px;min-width:22px}"
        # --- Footer -------------------------------------------------------------------
        ".synapse-report-footer{width:100%;max-width:var(--maxw);margin:40px auto 0;padding:22px 28px 30px;border-top:1px solid var(--line);display:flex;flex-wrap:wrap;gap:10px 20px;align-items:center;font-family:var(--mono);font-size:12px;color:var(--ink-faint)}.synapse-report-footer .footer-note{margin-left:auto}"
        # --- Responsive + print -------------------------------------------------------
        "@media(max-width:1100px){.layout{grid-template-columns:1fr}.report-toc{position:static;max-height:none;overflow:visible;background:transparent;padding:0}.report-toc ol:before{display:none}.banner-inner{gap:18px}.risk-tiles{grid-template-columns:repeat(2,1fr)}.finding-grid{grid-template-columns:1fr}.record,.request,.signal-record{grid-template-columns:1fr;margin-left:10px}.controls input{min-width:100%}.stat-grid,.cards{display:block}.stat-card,.card{margin:8px 0}.synapse-report-footer .footer-note{margin-left:0}}"
        "@media(max-width:760px){.banner-note{display:none}.report-strip{width:calc(100% - 36px);max-width:calc(100% - 36px);padding:0}.risk-tiles{grid-template-columns:1fr}.risk-panel{padding:18px}.meta{width:calc(100% - 36px);max-width:calc(100% - 36px);margin-left:18px;margin-right:18px}.wrap{padding-left:18px;padding-right:18px}table{min-width:680px}.exec-summary{padding-left:18px;padding-right:18px}}"
        "@media print{body{background:#fff;color:#111827}.banner,.meta,.layer,.block,.table-wrap,.finding,.stat-card{break-inside:avoid}.banner-art,.banner-fade,.switch,.controls{display:none!important}.report-toc{position:static}.layout{display:block}.wrap{max-width:none;padding:0 18px 28px}.meta,.table-wrap,.finding,.stat-card{background:#fff;border-color:#c9ced8}.layer-head h2,tbody td,p,.summary-list li,code,.mono{color:#111827}thead th{background:#eef1f5;color:#111827}.synapse-report-footer{max-width:none;color:#344054}}"
    )


def escape_text(value: Any) -> str:
    import html

    return html.escape(str("" if value is None else value), quote=True)


def escape_label(value: Any) -> str:
    text = str(value or "").replace("_", " ")
    result = []
    for char in text:
        if char.isupper() and result:
            result.append(" ")
        result.append(char)
    return escape_text("".join(result).title())
